workspace(name = "main")

load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

load("external.bzl", "external_1", "external_2", "external_3")

# Case F: Three extern workspaces are imported under the same name, and there is
# a load() statement at the top of the workspace. The repositories are imported
# from tar balls with an http_archive() rule. The second workspace is imported
# from the WORKSPACE file, the other two from a function in a .bzl file.
#
# In this case, the overriding works, and the last instance instance wins.

external_1()

http_archive(
    name = "external",
    url = "file:../external_2.tar",
    strip_prefix = "external_2",
)

external_3()
